platform :ios ,'7.0'
pod 'AFNetworking'
pod 'SDWebImage', '~> 3.7.5'
pod 'MMDrawerController', '~> 0.5.7'
pod 'FDFullscreenPopGesture', '1.1'
pod 'MJRefresh', '~> 3.1.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'DZNEmptyDataSet'
pod 'SinaWeibo', '~> 0.0.1'
pod 'WeiboSDK', '~> 3.1.3'
pod 'FCUUID'